sudo: false
language: scala
scala:
  - 2.12.12
  - 2.13.3
jdk:
  - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION $([ "$TRAVIS_SCALA_VERSION" != "${TRAVIS_SCALA_VERSION#2.13}" ] && echo 'test; docs/mdoc' || echo 'test')

cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
