name: routing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.12, 2.13.4]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2
      - name: sbt test
        run: - sbt ++$SCALA_VERSION $([ "$SCALA_VERSION" != "${SCALA_VERSION#2.13}" ] && echo 'test; docs/mdoc' || echo 'test')
